In [132]:
import numpy as np 
a = np.array ([1,2,3,4]) 
print (a)  
print (a.dtype) 

[1 2 3 4]
int64


In [133]:
a = np.array ( [ [1,2,3,4,5,6,7] , [8,9,10,11,12,13,14] ]) 
print (a) 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [134]:
a[1,5] 


np.int64(13)

AttributeError: module 'numpy' has no attribute 'indentity'

# Ndarray

In [120]:
import numpy as np 


## 1d array 
arr1 = np.array ( [1,2,3,4,5,6,7,8,9,10] )  



## 2d array 
arr2 = np.array ( [ [1,2,3,4,5] , 
         [6,7,8,9,10] ] ) 


## 3d array 
arr3 = np.array ( [ [ [1,2,3,4,5] , 
           [6,7,8,9,10] ] , 

           [ [11,12,13,14,15] ,
           [16,17,18,19,20] ] ,

           [ [ 21,22,23,24,25] , 
             [26,27,28,29,30 ] ]
                  ] )  



# Array Attributes

In [124]:
# dimension 
print("The dimension is : ") 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 


#shape 
print("The shape is : ") 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 


#data type 
print("The data type is : ") 
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size 
print("The size is : ") 
print(arr1.size)
print(arr2.size)
print(arr3.size)

The dimension is : 
1
2
3
The shape is : 
(10,)
(2, 5)
(3, 2, 5)
The data type is : 
int64
int64
int64
The size is : 
10
10
30


# Ndarray data type

In [20]:
arr = np.array ([1,2,3] ) 
print (arr) 
print (arr.dtype)
arr1 = np.array ([1.67 , 4.44 , 9.47] ) 
print (arr1) 
print (arr1.dtype)

[1 2 3]
int64
[1.67 4.44 9.47]
float64


In [23]:
arr = np.array ( [1,2,4.666] ) 
print (arr.dtype) 


float64


In [24]:
a1 = np.array ( [1,3,4,6,5.777,5.333, 'BD'] ) 
# unicode
# One standard system to represent characters from all languages.

print (a1.dtype) 


<U32


In [25]:
a1 = np.array ( [1,3,4,6,5.777,5.333, "BANGLADESH" ] ) 
print (a1.dtype) 

<U32


In [27]:
import numpy as np 


arr = np.array ([True , False , True ] , dtype = bool ) 


print (arr) 
print (arr.dtype) 


[ True False  True]
bool


In [35]:
arr_num = np.array ([0 , 1 , 2, -3] ) 
bool_arr = arr_num.astype (bool) 
# data type change method।
print (bool_arr) 


[False  True  True  True]


In [33]:
import numpy as np 

a = np.array ( [True , False , True] ) 
b = np.array ( [True , True , False] ) 

result = a & b 
print ("The AND is : ") 
print (result) 

result = a | b 
print ("The OR is : ") 
print (result) 

result = ~a 
print ("The NOT is : ") 
print (result) 


result = ~b 
print ("The NOT is : ") 
print (result) 

The AND is : 
[ True False False]
The OR is : 
[ True  True  True]
The NOT is : 
[False  True False]
The NOT is : 
[False False  True]


In [34]:
arr = np.array ( [10,20,30,40,50] ) 
bool_arr = (arr > 15) & (arr < 35) 
print (bool_arr) 
print (arr[bool_arr]) 


[False  True  True False False]
[20 30]


# Selecting a data type for an array 


In [43]:
arr = np.array ([1,2,300] , dtype = np.int64 ) 
print (arr) 
print (arr.dtype) 


arr = np.array ([1,2,300]) 
arr = arr.astype(np.int16) 
print (arr) 
print (arr.dtype)   



arr = np.array ([1,2,300] , dtype = np.float64 ) 
print (arr) 
print (arr.dtype) 

[  1   2 300]
int64
[  1   2 300]
int16
[  1.   2. 300.]
float64


In [44]:
arr = np.array ( [1, True , 3.22 , "Hello"] ) 
print (arr) 
print (arr.dtype) 


['1' 'True' '3.22' 'Hello']
<U32


# List 


In [95]:
List = [10, 20 , 30 , 40 , 50, 60 , 70 , 4.5555] 

arr = np.array(List) 
print(arr) 
print (type (arr) ) 
print (arr.dtype) 

[10.     20.     30.     40.     50.     60.     70.      4.5555]
<class 'numpy.ndarray'>
float64


In [46]:
list = [10, 20 , 30 , 40 , 50, 60 , 70 , 4.5555] 

arr = np.array(list , dtype = np.int32)  
print(arr) 
print (type (arr) ) 
print (arr.dtype)

[10 20 30 40 50 60 70  4]
<class 'numpy.ndarray'>
int32


In [50]:
Mix_list =  [12, True , "Hello" , 12.444] 
arr = np.array(Mix_list) #, dtype = np.int32)  
print(arr) 
print (type (arr) ) 
print (arr.dtype)

['12' 'True' 'Hello' '12.444']
<class 'numpy.ndarray'>
<U32


In [55]:
arr = np.array ( [ [1,2,3,4,5] , 
         [6,7,8,9,10] ] )  

arr = np.array(arr) 
print (arr) 
print (type(arr) ) 
print (arr.dtype) 
print (arr.shape) 
print (arr.ndim ) 


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
int64
(2, 5)
2


# Tuple

In [66]:
tpl = (1,4,2,3) 
arr = np.array(tpl) 
print (arr) 
print (type(arr) ) 
print (arr.dtype) 
print (arr.shape) 
print (arr. ndim) 


arr = np.array (tpl , dtype = np.int32) 
print (arr.dtype) 


arr = arr.astype (np.int16) 
print (arr) 


[1 4 2 3]
<class 'numpy.ndarray'>
int64
(4,)
1
int32
[1 4 2 3]


# SET

In [99]:
import numpy as np 

st = {1,2,3,4,5,6} 
arr = np.array (st) 
print (arr) 
print (type(arr) ) 
print (arr.dtype) 
print (arr.shape) 
print (arr. ndim) 




{1, 2, 3, 4, 5, 6}
<class 'numpy.ndarray'>
object
()
0


# dictionary 


In [108]:
dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items() 

print (values)
print (items) 


dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


In [107]:
arr = np.array(keys)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)




dict_keys(['a', 'b', 'c'])
<class 'numpy.ndarray'>
object
()
0
1


In [105]:
arr = np.array(list (items) ) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

TypeError: 'list' object is not callable

# Creating ndarray from scratch

In [113]:
arr = np.zeros( (1,3 ) ) 
print(arr)
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 


arr1 = np.zeros( (2,3 ) ) 
print(arr1)
print(arr1.shape)  
print(arr1.size)
print (arr1.ndim) 
print (arr1.dtype) 

[[0. 0. 0.]]
(1, 3)
3
2
float64
[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)
6
2
float64


In [115]:
arr1 = np.zeros( (2,3 ) , dtype = np.int8) 
print(arr1)
print(arr1.shape)  
print(arr1.size)
print (arr1.ndim) 
print (arr1.dtype) 

[[0 0 0]
 [0 0 0]]
(2, 3)
6
2
int8


In [126]:
arr = np.zeros_like (arr3) 
print(arr3) 
print(arr.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
(3, 2, 5)


In [127]:
arr = np.ones( (1,3 ) ) 
print(arr)
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 


[[1. 1. 1.]]
(1, 3)
3
2
float64


In [130]:
arr1 = np.ones( (4,3 ) , dtype = np.int8) 
print(arr1) 
print (type (arr1) )
print(arr1.shape)  
print(arr1.size)
print (arr1.ndim) 
print (arr1.dtype) 

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
(4, 3)
12
2
int8


In [135]:
arr1 = np.ones( (3 , 4 , 3 ) , dtype = np.int8) 
print(arr1) 
print (type (arr1) )
print(arr1.shape)  
print(arr1.size)
print (arr1.ndim) 
print (arr1.dtype) 

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
(3, 4, 3)
36
3
int8


In [136]:
arr1 = np.ones_like (arr3) 
print(arr1) 
print(arr1.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
(3, 2, 5)


In [142]:
arr = np.empty( (4 , 3 ) , dtype = np.int8) 
print(arr) 
print (type (arr) )
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
(4, 3)
12
2
int8


In [148]:
arr = np.empty_like (arr) 
print(arr) 
print(arr.shape)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]
(3, 2, 5)


In [153]:
arr = np.full((4,3 ) , 10 ) 
print(arr) 
print (type (arr) )
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
(4, 3)
12
2
int64


In [154]:
arr = np.full((4,3 ) , np.inf) 
print(arr) 
print (type (arr) )
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
(4, 3)
12
2
float64


In [155]:
arr = np.full((4,3 ) , True ) 
print(arr) 
print (type (arr) )
print(arr.shape)  
print(arr.size)
print (arr.ndim) 
print (arr.dtype) 

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
(4, 3)
12
2
bool


In [167]:
arr = np.full((4,3 ) , np.inf) 
arr = np.full_like (arr3 , np.inf ) 
print (arr) 
print(arr.shape)

[[[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808
   -9223372036854775808 -9223372036854775808]]]
(3, 2, 5)


In [168]:
arr = np.full((4,3 ) , np.inf) 
arr = np.full_like (arr3 , np.inf , dtype = np.float64 ) 
print (arr) 
print(arr.shape)

[[[inf inf inf inf inf]
  [inf inf inf inf inf]]

 [[inf inf inf inf inf]
  [inf inf inf inf inf]]

 [[inf inf inf inf inf]
  [inf inf inf inf inf]]]
(3, 2, 5)


In [165]:
arr2 = np.full((4,3), 10) 
print(arr2)
print(arr2.shape)
print(arr2.dtype)


[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
(4, 3)
int64


In [166]:
arr2 = np.full((4,3), 10.5 ) 
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]
(4, 3)
float64


# array creation with random values

In [4]:
import numpy as np

arr = np.random.rand(2,3) 
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[[0.7862695  0.87757069 0.6446297 ]
 [0.94367543 0.79816351 0.83147718]]
<class 'numpy.ndarray'>
(2, 3)
6
2
float64


In [10]:
import numpy as np

arr = np.random.randint(1,10, (2,3) )  
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[[7 7 8]
 [6 1 5]]
<class 'numpy.ndarray'>
(2, 3)
6
2
int32


In [13]:
import numpy as np

arr = np.random.randint(1,10, (2,))  
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[8 9]
<class 'numpy.ndarray'>
(2,)
2
1
int32


In [14]:
import numpy as np

arr = np.random.randint(1,10, (10, 10))  
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[[5 4 3 8 1 8 7 9 8 5]
 [1 4 7 7 7 6 1 8 4 6]
 [4 3 1 8 4 1 4 4 8 9]
 [6 6 4 1 7 7 4 6 7 2]
 [1 5 4 5 5 2 2 7 2 9]
 [8 4 6 1 1 4 2 7 3 1]
 [5 7 1 7 3 9 6 8 2 9]
 [8 1 9 5 1 8 9 9 3 4]
 [9 1 2 8 9 2 4 6 5 5]
 [3 5 7 6 8 1 2 6 9 8]]
<class 'numpy.ndarray'>
(10, 10)
100
2
int32


In [19]:
import numpy as np

arr = np.random.uniform(50,100 , (3, 4))  
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[[76.54314672 61.86356666 78.28334431 84.98046458]
 [87.64114685 55.52934909 68.37163217 95.51687118]
 [71.38092958 69.44927456 54.44705122 56.02934344]]
<class 'numpy.ndarray'>
(3, 4)
12
2
float64


In [20]:
import numpy as np

arr = np.random.uniform(50,100 , (3 , 3, 4))  
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)


[[[80.22889753 97.94205156 78.76988111 80.0650837 ]
  [73.92236701 56.18830381 52.51637935 69.85089682]
  [54.84627769 96.05914644 60.95651903 71.3136651 ]]

 [[57.18103475 85.62530803 64.08264998 70.78809049]
  [62.78023618 70.47843999 66.03335263 74.35441504]
  [60.62994945 91.98565585 94.87827402 84.40861461]]

 [[81.29865854 56.32917549 64.96975629 50.94125728]
  [59.00081078 64.50326429 68.92777605 93.026932  ]
  [64.99488857 50.80198643 73.4968241  66.37297962]]]
<class 'numpy.ndarray'>
(3, 3, 4)
36
3
float64


# array creation with range functions

In [22]:
arr = np.arange ( 1 , 10 , 1 ) 
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
9
1
int64


In [23]:
arr = np.arange ( 1 , 10 , 2 ) 
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[1 3 5 7 9]
<class 'numpy.ndarray'>
(5,)
5
1
int64


In [24]:
arr = np.arange ( 1 , 10 , 1 ).reshape(3,3) 
print(arr) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
9
2
int64


In [26]:
arr = np.arange ( 1 , 10 , 1 )
matrix = arr.reshape(3,3) 
print(arr)  
print (matrix) 
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(9,)
9
1
int64


In [27]:
import numpy as np

arr = np.linspace(1, 10, 5)
print(arr)
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>
(5,)
5
1
float64


In [28]:
arr = np.linspace(0, 1, 6)
print(arr)


[0.  0.2 0.4 0.6 0.8 1. ]


In [29]:
import numpy as np

arr = np.linspace(1, 10, 15)
print(arr)
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
(15,)
15
1
float64


In [30]:
import numpy as np

arr = np.logspace(0, 3, 4)
print(arr)


[   1.   10.  100. 1000.]


In [31]:
arr = np.logspace(0, 4, 5, base=2)
print(arr)


[ 1.  2.  4.  8. 16.]


In [34]:
import numpy as np

arr = np.logspace(0, 4, 5)
print(arr)
print(type(arr))
print(arr.shape)  
print(arr.size)
print(arr.ndim) 
print(arr.dtype)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
<class 'numpy.ndarray'>
(5,)
5
1
float64


In [35]:
import numpy as np

arr = np.logspace(0, 4, 6)
print(arr)


[1.00000000e+00 6.30957344e+00 3.98107171e+01 2.51188643e+02
 1.58489319e+03 1.00000000e+04]


In [36]:
import numpy as np

arr = np.logspace(0, 4, 6 , base = 2 ) 
print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


In [37]:

diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [38]:
identity_mat = np.eye(4)
mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
import numpy as np

arr = np.diag([1, 2, 3])
print(arr)


[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [40]:
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
arr = np.eye(3) * 5
print(arr)


[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


In [42]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(np.diag(mat))


[1 5 9]


In [43]:
arr = np.eye(4)
print(arr) 
print (arr.shape) 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [44]:
arr = np.eye(3,4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [45]:
arr = np.eye(3,4 , -1)
print(arr)


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [46]:
arr = np.eye(3,4 , 1)
print(arr)


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ndarray Indexing and Slicing

In [52]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print(arr1)
print(arr2)


[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [53]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])


arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print(arr1)
print(arr2)



print(arr1 [2] )


[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]
3


In [55]:
import numpy as np


arr1 = np.array([1, 2, 3, 4, 5])


arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print(arr1)
arr1[2] = 100

print(arr1)


[1 2 3 4 5]
[  1   2 100   4   5]


In [56]:
import numpy as np


arr1 = np.array([1, 2, 3, 4, 5])


arr2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

print(arr1)
print(arr2)


arr2[0][2] = 100

print(arr2)


[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]
[[ 10  20 100]
 [ 40  50  60]]


In [57]:
arr1_mod = arr1[1:4]
arr1[1] = 2
arr1_mod[2] = 200
print(arr1_mod)
print(arr1)


[  2   3 200]
[1 2 3 4 5]


In [58]:
arr1_mod = arr1[1:4].copy() 
arr1[1] = 2
arr1_mod[2] = 200
print(arr1_mod)
print(arr1)


[  2   3 200]
[1 2 3 4 5]


In [59]:
row_0 = arr2[0:1 ,]
row_1= arr2[1: , ]
col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]
print(col_0)
print(col_1)
portion = arr2[:: , 0:2] 
print(portion)

[[10]
 [40]]
[[20]
 [50]]
[[10 20]
 [40 50]]


In [60]:
row_0 = arr2[0:1 ,]
row_1= arr2[1: , ]

print(row_0)
print(row_1)

[[ 10  20 100]]
[[40 50 60]]


# Ndarray Copy Advanced Indexing and Iteration


In [61]:

lst = np.array([ 10 , 20 ,30 ,40 ]) 

values = lst[[0,3,1]]

print(values)

[10 40 20]


In [67]:
values = lst[[2, 3]]
print(values)


[30 40]


In [63]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2 >1])
arr2[arr2>2] = 0 

print(arr2)

[[ 10  20 100]
 [ 40  50  60]]
[20 60]
[ 10  20 100  40  50  60]
[[0 0 0]
 [0 0 0]]


In [68]:
print(arr2)

[[0 0 0]
 [0 0 0]]


In [72]:
arr  = np.array([[10,20,30] , [100,200,300] ] )
# iteration 
print(arr)

[[ 10  20  30]
 [100 200 300]]


In [73]:
for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300


In [80]:
arr  = np.array([[10,20,30] , [100,200,300] ] )
print(arr)  
for i in arr : 
    for j in i : 
        print (j ) 

[[ 10  20  30]
 [100 200 300]]
10
20
30
100
200
300


# ndarray Manipulation 1

In [76]:

import numpy as np 

arr = np.random.randint(1 ,100 , size =(10,5))  

arr.shape

(10, 5)

In [77]:

b = arr.reshape(5,10)

b.shape
b.ndim 
b

array([[62, 96,  4, 82, 16, 79, 81, 20, 68, 49],
       [30, 17, 25, 89, 60, 44, 93, 21, 45, 33],
       [14, 44, 24, 72, 23, 33,  3, 78, 18, 75],
       [80, 21, 97, 77, 74, 95, 58, 16, 49, 55],
       [ 5, 38, 26, 29, 80, 96, 41, 43, 25, 53]], dtype=int32)

In [83]:
flatten = b.flatten()
print(flatten.ndim)
flatten

1


array([20, 20, 27, 21, 29, 21], dtype=int32)

In [89]:
flatten = b.flatten()
print(flatten.ndim)
flatten
column_wise_flattening = np.ravel(b,order= 'F') 
print(column_wise_flattening) 

1
[20 28 29 20 28 24]


In [90]:
a = np.random.randint(1 ,10 , size =(2,3))
b = np.random.randint(20 ,30 , size =(2,3)) 
print (a ) 
print (b)

[[2 4 5]
 [5 9 9]]
[[29 21 25]
 [22 26 27]]


In [91]:

con_row = np.concatenate((a,b),axis=0) # row wise 

print(con_row)

con_col = np.concatenate((a,b), axis = 1) # column wise 

print(con_col)

[[ 2  4  5]
 [ 5  9  9]
 [29 21 25]
 [22 26 27]]
[[ 2  4  5 29 21 25]
 [ 5  9  9 22 26 27]]


In [94]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6]


In [95]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c = np.concatenate((a, b), axis=0)  # row-wise
print(c)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [96]:
c = np.concatenate((a, b), axis=1)  # column-wise
print(c)


[[1 2 5 6]
 [3 4 7 8]]


# ndarray Manipulation 2

In [92]:
mat = np.array([[10,20,30],
                [30,40,50]
               ])

transpose = mat.T
print(transpose) 

[[10 30]
 [20 40]
 [30 50]]


In [93]:
a = np.random.randint(1 ,10 , size =(10,))
print(a)
splitted_array = np.array_split(a,3) 
print(splitted_array)

[7 2 7 9 4 1 6 9 8 5]
[array([7, 2, 7, 9], dtype=int32), array([4, 1, 6], dtype=int32), array([9, 8, 5], dtype=int32)]


# arithmetic operator and mathematical functions

In [97]:
x = np.array([ 10 , 8 , 30 , 100 ])
y = np.array([ 2 , 3 ,4  ,5 ]) 

add = np.add(x,y) 
print(add)

sub = x-y 
print(sub)

mul = x*y 
print(mul) 

div = x/y 
print(div) 

remainder = x % y

print(remainder) 

[ 12  11  34 105]
[ 8  5 26 95]
[ 20  24 120 500]
[ 5.          2.66666667  7.5        20.        ]
[0 2 2 0]


In [98]:
sin_val = np.sin(x)
print(sin_val) 

cos_val = np.cos(x)
print(cos_val) 

deg_con = np.rad2deg(x)
print(deg_con)


[-0.54402111  0.98935825 -0.98803162 -0.50636564]
[-0.83907153 -0.14550003  0.15425145  0.86231887]
[ 572.95779513  458.3662361  1718.87338539 5729.57795131]


In [99]:
x = np.array([ 10 , 8 , 16 , 100 ])
base_10_log_val = np.log10(x)
print(base_10_log_val)


two_diye_bhag = np.log2(x) 
print(two_diye_bhag)

sqrt= np.sqrt(x)
print(sqrt)



[1.         0.90308999 1.20411998 2.        ]
[3.32192809 3.         4.         6.64385619]
[ 3.16227766  2.82842712  4.         10.        ]


In [100]:

# different 
s = np.sum(x)
print(s)

#prefix sum 
cumul =np.cumulative_sum(x)
print(cumul)

134
[ 10  18  34 134]


In [101]:
x = np.array([ 10 , 8 , 16 , 100 ])
y = np.array([ 2 , 3 ,16  ,5 ]) 

greater_than = x>y 

print(greater_than)

equal = x==y 

print(equal) 

# all () -> shob true kina 
# any() -> jekono ekta true ase kina 

print(np.all(greater_than)) 

print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


In [102]:
x = np.array([ 10 , 8 , 16 , 100 ])

z = x.copy()

print(z) 

z.sort()

print(z)

[ 10   8  16 100]
[  8  10  16 100]


In [103]:
print(x)
sort_arr = np.sort(x) 

print(sort_arr)

print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [105]:
# 2d array sorting 
mat = np.array([[10,3,5],[8,4,9]])

# horizon axis = 1 

hor_sort = np.sort(mat,axis=1)
print(hor_sort)

vert_sort = np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [106]:

print(x)

[ 10   8  16 100]


In [107]:
index = np.where(x==8) # returns index
print(index)

arr = np.where(x>8,x,0) # returns array 
print(arr)

(array([1]),)
[ 10   0  16 100]


In [108]:
print (mat)

[[10  3  5]
 [ 8  4  9]]


In [109]:
index = np.where(mat>8) # returns index
print(index)

arr = np.where(mat>8,mat,0) # returns array 
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [110]:
x = np.array([ 10,100 , 8 , 16 , 100 ])

maximum_value_indx = np.argmax(x) 
minimum_value_indx = np.argmin(x)

print(maximum_value_indx)
print(minimum_value_indx)

1
2


In [111]:
a = np.random.randint(1 ,100 , size =(100,))
print(a)

[87 98 29 18 41  8 67 78 81 71 45 47 37 61 33 69 44 81 72 72 65 56 60 28
 47 84 97 16 61 13 14 68 12 16 29 31 21 47 69 93 61 21 22 70 39 25 45 30
  6 15  9 40 70 15 35 58 48 47 46 96  3 60 66 65 34 84 22 35 40 13 62  2
 22 12 87 31 29 58 31 48 31 49  7 81 17 38 93 79 45 52 92 11 71 72 69  5
 84 44  6 73]


In [112]:
value_great_than_60 = np.count_nonzero(a==97)
print(value_great_than_60)

1


In [113]:
unique_value,count = np.unique(a,return_counts=True)

print(unique_value) 
print(count)

[ 2  3  5  6  7  8  9 11 12 13 14 15 16 17 18 21 22 25 28 29 30 31 33 34
 35 37 38 39 40 41 44 45 46 47 48 49 52 56 58 60 61 62 65 66 67 68 69 70
 71 72 73 78 79 81 84 87 92 93 96 97 98]
[1 1 1 2 1 1 1 1 2 2 1 2 2 1 1 2 3 1 1 3 1 4 1 1 2 1 1 1 2 1 2 3 1 4 2 1 1
 1 2 2 3 1 2 1 1 1 3 2 2 3 1 1 1 3 3 2 1 2 1 1 1]


# statistical function

In [115]:
# Mean
import numpy as np
marks = np.array([70, 80, 90, 85, 75])
avg_marks = np.mean(marks)
print("Average Marks:", avg_marks)


Average Marks: 80.0


In [117]:
prices = np.array([100, 200, 300, 400, 5000])
median_price = np.median(prices)
print("Median Price:", median_price)


Median Price: 300.0


In [118]:
marks = np.array([70, 80, 90, 85, 75])
std_marks = np.std(marks)
print("Standard Deviation:", std_marks)


Standard Deviation: 7.0710678118654755


In [119]:
np.var(marks)


np.float64(50.0)

In [121]:
var_marks = np.var(marks)
print("Variance of Marks:", var_marks)


Variance of Marks: 50.0


In [122]:
total_marks = np.sum(marks)
print("Total Marks:", total_marks)


Total Marks: 400


In [123]:
max_mark = np.max(marks)
print("Maximum Marks:", max_mark)


Maximum Marks: 90


In [124]:
min_mark = np.min(marks)
print("Minimum Marks:", min_mark)


Minimum Marks: 70


In [125]:
p50 = np.percentile(marks, 50)  # Median
p90 = np.percentile(marks, 90)  # Top 10% boundary
print("50th Percentile (Median):", p50)
print("90th Percentile:", p90)


50th Percentile (Median): 80.0
90th Percentile: 88.0


In [127]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12] 
])

# a er column and b er row same length hote hobe 
dot_product = np.dot(A,B)
print(dot_product)


# trace 
print(np.trace(B) ) 

[[ 58  64]
 [139 154]]
17


In [128]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

-9.51619735392994e-16
2


In [129]:

A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
